package:
    type:           yii2-extension
    name:           hipanel
    title:          AdvancedHosters implementation of HiPanel
    headline:       AdvancedHosters HiPanel
    homepage:       https://advancedhosters.com/
    keywords:       advanced hosters, hipanel, control panel, hosting, domains
    namespace:      adavancedhosters\hipanel
    description:    |
        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.

        This package is HiPanel build for [AHnames](https://ahnames.com) domain registrator.
